<?php

namespace Domains\Context\PlayersInformation\Domain\Model\DataSource\DataSourceItem;

class SourceItemStatusEnum
{

    public const CREATED = 'CREATED';

    public const SUCCESS = 'SUCCESS';

    public const PO_MISSING = 'PO_MISSING';

    public const ASSET_CODE_MISSING = 'ASSET_CODE_MISSING';

    public const EXTERNAL_INVOICE_ID_MISSING = 'EXTERNAL_INVOICE_ID_MISSING';

    public const ASSET_CODE_NOT_FOUND = 'ASSET_CODE_NOT_FOUND';

    public const PO_NUMBER_NOT_FOUND = 'PO_NUMBER_NOT_FOUND';

    public const DUPLICATE_PO_IN_PROPRLI = 'DUPLICATE_PO_IN_PROPRLI';

    public const INVOICE_VALUE_CHANGED = 'INVOICE_VALUE_CHANGED';

    public const SUCCESSFULLY_IMPORTED_PREVIOUSLY = 'SUCCESSFULLY_IMPORTED_PREVIOUSLY';

    public const RECURRING_REGISTRY_ENTRIES = 'RECURRING_REGISTRY_ENTRIES';

    public const STATUS = [self::CREATED, self::SUCCESS, self::PO_MISSING, self::INVOICE_VALUE_CHANGED, self::ASSET_CODE_MISSING, self::EXTERNAL_INVOICE_ID_MISSING, self::ASSET_CODE_NOT_FOUND, SELF::DUPLICATE_PO_IN_PROPRLI, self::PO_NUMBER_NOT_FOUND, self::SUCCESSFULLY_IMPORTED_PREVIOUSLY, self::RECURRING_REGISTRY_ENTRIES];
}
